import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// The app (and, when Accessibility exposes it, the text element) that should receive a transcript.
struct PasteTarget {
    let processIdentifier: pid_t
    let bundleIdentifier: String?
    let appName: String?
    let focusedElement: AXUIElement?
    /// The focused element is a password field.
    let isSecureField: Bool

    var isOwnApp: Bool { processIdentifier == ProcessInfo.processInfo.processIdentifier }
}

enum PasteOutcome: Equatable, Sendable {
    case pasted
    case copied(reason: CopyReason)
    /// Refused because a password field is focused; nothing was pasted or copied.
    case blockedSecureField

    enum CopyReason: Equatable, Sendable {
        case needsAccessibility
        case noTarget
        case clipboardOnly
    }

    var pasted: Bool { self == .pasted }

    var message: String {
        switch self {
        case .pasted: "Pasted"
        case .copied(.needsAccessibility): "Copied — allow Accessibility to paste automatically"
        case .copied(.noTarget): "Copied to clipboard — press ⌘V to paste"
        case .copied(.clipboardOnly): "Copied to clipboard"
        case .blockedSecureField: "Not typed into a password field"
        }
    }
}

@MainActor
protocol Pasting: AnyObject {
    func captureTarget() -> PasteTarget?
    func insert(_ text: String, into target: PasteTarget?, restoreClipboard: Bool) async -> PasteOutcome
}

@MainActor
final class PasteService: Pasting {
    /// Pasteboard types that clipboard managers treat as "don't record this".
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    func captureTarget() -> PasteTarget? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        let focused = PermissionService.hasAccessibilityPermission() ? Self.focusedElement(in: app.processIdentifier) : nil
        return PasteTarget(
            processIdentifier: app.processIdentifier,
            bundleIdentifier: app.bundleIdentifier,
            appName: app.localizedName,
            focusedElement: focused,
            isSecureField: focused.map(Self.isSecureField) ?? false
        )
    }

    func insert(_ text: String, into target: PasteTarget?, restoreClipboard: Bool) async -> PasteOutcome {
        guard !text.isEmpty else { return .copied(reason: .clipboardOnly) }
        let target = target ?? captureTarget()

        if let target, target.isOwnApp {
            return insertIntoOwnWindow(text)
        }

        guard PermissionService.hasAccessibilityPermission() else {
            writeToClipboard(text, transient: false)
            return .copied(reason: .needsAccessibility)
        }
        guard let target, NSRunningApplication(processIdentifier: target.processIdentifier) != nil else {
            writeToClipboard(text, transient: false)
            return .copied(reason: .noTarget)
        }

        await bringToFront(target)

        let element = target.focusedElement ?? Self.focusedElement(in: target.processIdentifier)
        // Focus may have moved to a password field since recording started.
        if target.isSecureField || element.map(Self.isSecureField) == true {
            return .blockedSecureField
        }
        let finalText = TranscriptPostProcessor.applySmartSpacing(text, precedingCharacter: element.flatMap(Self.characterBeforeCaret))

        let pasteboard = NSPasteboard.general
        let snapshot = restoreClipboard ? PasteboardSnapshot(pasteboard) : nil
        writeToClipboard(finalText, transient: restoreClipboard)
        let ourChangeCount = pasteboard.changeCount

        Self.postCommandV()

        // The target app reads the clipboard asynchronously when it handles ⌘V. Give it time before
        // restoring, and never clobber something the user copied in the meantime.
        try? await Task.sleep(for: .milliseconds(700))
        if pasteboard.changeCount == ourChangeCount {
            if let snapshot {
                snapshot.restore(to: pasteboard)
            }
        }
        return .pasted
    }

    // MARK: - Own window

    /// Dictating into Flowtype's own fields (e.g. Notes) inserts directly instead of synthesizing keys.
    private func insertIntoOwnWindow(_ text: String) -> PasteOutcome {
        if let textView = NSApp.keyWindow?.firstResponder as? NSTextView, textView.isEditable {
            let previous = Self.character(before: textView.selectedRange().location, in: textView.string)
            let finalText = TranscriptPostProcessor.applySmartSpacing(text, precedingCharacter: previous)
            textView.insertText(finalText, replacementRange: textView.selectedRange())
            return .pasted
        }
        writeToClipboard(text, transient: false)
        return .copied(reason: .noTarget)
    }

    // MARK: - Clipboard

    private func writeToClipboard(_ text: String, transient: Bool) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            for type in Self.transientTypes {
                item.setString("", forType: type)
            }
        }
        pasteboard.writeObjects([item])
    }

    // MARK: - Focus

    private func bringToFront(_ target: PasteTarget) async {
        guard let app = NSRunningApplication(processIdentifier: target.processIdentifier) else { return }
        if NSWorkspace.shared.frontmostApplication?.processIdentifier != target.processIdentifier {
            app.activate()
            // Activation is asynchronous; wait until the app is actually frontmost (up to ~0.6 s).
            for _ in 0..<12 {
                try? await Task.sleep(for: .milliseconds(50))
                if NSWorkspace.shared.frontmostApplication?.processIdentifier == target.processIdentifier { break }
            }
            if let element = target.focusedElement {
                AXUIElementSetAttributeValue(element, kAXFocusedAttribute as CFString, kCFBooleanTrue)
            }
            try? await Task.sleep(for: .milliseconds(60))
        }
    }

    private static func focusedElement(in pid: pid_t) -> AXUIElement? {
        let app = AXUIElementCreateApplication(pid)
        AXUIElementSetMessagingTimeout(app, 0.25)
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(app, kAXFocusedUIElementAttribute as CFString, &value) == .success,
              let value,
              CFGetTypeID(value) == AXUIElementGetTypeID() else {
            return nil
        }
        return (value as! AXUIElement)
    }

    private static func isSecureField(_ element: AXUIElement) -> Bool {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXSubroleAttribute as CFString, &value) == .success else {
            return false
        }
        return (value as? String) == (kAXSecureTextFieldSubrole as String)
    }

    private static func characterBeforeCaret(in element: AXUIElement) -> Character? {
        AXUIElementSetMessagingTimeout(element, 0.2)
        var rangeValue: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &rangeValue) == .success,
              let rangeValue,
              CFGetTypeID(rangeValue) == AXValueGetTypeID() else {
            return nil
        }
        var range = CFRange()
        guard AXValueGetValue(rangeValue as! AXValue, .cfRange, &range), range.location > 0 else { return nil }

        var previousRange = CFRange(location: range.location - 1, length: 1)
        guard let previousValue = AXValueCreate(.cfRange, &previousRange) else { return nil }
        var stringValue: CFTypeRef?
        guard AXUIElementCopyParameterizedAttributeValue(
            element,
            kAXStringForRangeParameterizedAttribute as CFString,
            previousValue,
            &stringValue
        ) == .success, let string = stringValue as? String else {
            return nil
        }
        return string.last
    }

    private static func character(before location: Int, in string: String) -> Character? {
        let utf16 = string.utf16
        guard location > 0, location <= utf16.count else { return nil }
        let index = utf16.index(utf16.startIndex, offsetBy: location)
        guard let stringIndex = index.samePosition(in: string), stringIndex > string.startIndex else { return nil }
        return string[string.index(before: stringIndex)]
    }

    // MARK: - Keystroke

    private static func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        // Keep the user's physical keys (e.g. a still-held shortcut) from leaking into the paste.
        source?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents],
            state: .eventSuppressionStateSuppressionInterval
        )
        let keyCode = KeyboardLayout.keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        keyDown?.flags = .maskCommand
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cgSessionEventTap)
        keyUp?.post(tap: .cgSessionEventTap)
    }
}

/// A full copy of the clipboard, including images, files and rich text.
private struct PasteboardSnapshot {
    private let items: [[NSPasteboard.PasteboardType: Data]]

    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    entry[type] = data
                }
            }
            return entry
        }
    }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entry in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

enum KeyboardLayout {
    /// Finds the virtual key code that produces `character` with ⌘ in the current keyboard layout,
    /// so ⌘V still pastes on Dvorak, AZERTY and similar layouts.
    static func keyCode(for character: Character) -> CGKeyCode? {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let layoutPointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return nil
        }
        let layoutData = Unmanaged<CFData>.fromOpaque(layoutPointer).takeUnretainedValue() as Data
        let target = String(character).lowercased()

        return layoutData.withUnsafeBytes { buffer -> CGKeyCode? in
            guard let layout = buffer.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return nil }
            for keyCode in 0..<128 {
                var deadKeyState: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(
                    layout,
                    UInt16(keyCode),
                    UInt16(kUCKeyActionDown),
                    // Translate with ⌘ held: layouts like "Dvorak – QWERTY ⌘" switch keys under Command.
                    UInt32((cmdKey >> 8) & 0xFF),
                    UInt32(LMGetKbdType()),
                    OptionBits(kUCKeyTranslateNoDeadKeysBit),
                    &deadKeyState,
                    chars.count,
                    &length,
                    &chars
                )
                if status == noErr, length > 0, String(utf16CodeUnits: chars, count: length).lowercased() == target {
                    return CGKeyCode(keyCode)
                }
            }
            return nil
        }
    }
}
